# Generated by Django 5.2 on 2025-11-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('duration', models.CharField(max_length=20)),
                ('hike_image_url', models.URLField(blank=True, default='', max_length=250)),
                ('visible', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('details_url', models.URLField(blank=True, default='', max_length=250)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('movie', 'Movie'), ('link', 'Link'), ('gallery', 'Gallery'), ('other', 'Other'), ('map', 'Map'), ('report', 'Report'), ('gps', 'GPS')], default='image', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('visible', models.IntegerField(default=1)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiking.hike')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
