# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=1000)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiking.Hike')),
            ],
        ),
    ]
