# Generated by Django 4.2.7 on 2024-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('movie', 'Movie'), ('link', 'Link'), ('gallery', 'Gallery'), ('other', 'Other'), ('map', 'Map'), ('report', 'Report'), ('gps', 'GPS')], default='image', max_length=30),
        ),
    ]
