# Generated by Django 5.2 on 2025-11-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='campground_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='indoor_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='kilometers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='wild_campsite_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='wild_rough_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='with_who',
            field=models.CharField(blank=True, default='Ingeborg', max_length=20, null=True),
        ),
    ]
