# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
