# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_auto_20161007_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
