# Generated by Django 5.2 on 2025-11-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_hike_campground_nights_hike_days_hike_indoor_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='indoor_refuge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='indoor_staffed',
            field=models.IntegerField(default=0),
        ),
    ]
