# Generated by Django 5.2 on 2025-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0003_hike_indoor_refuge_hike_indoor_staffed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='indoor_unstaffed',
            field=models.IntegerField(default=0),
        ),
    ]
