# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0003_tripreport_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
