# Generated by Django 5.2 on 2025-11-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0004_hike_indoor_unstaffed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='indoor_nights',
        ),
    ]
