# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0004_tripreport_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='hike',
            name='country',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='trail',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
