# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0005_auto_20161020_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='trail',
        ),
        migrations.AlterField(
            model_name='hike',
            name='place',
            field=models.CharField(max_length=40),
        ),
    ]
