# Generated by Django 5.2 on 2025-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0005_remove_hike_indoor_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
