# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0006_auto_20161020_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
