# Generated by Django 5.2 on 2026-01-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0006_hike_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='hiking.hike')),
            ],
        ),
    ]
