# Generated by Django 5.2 on 2026-01-04 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0007_hikepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikepoint',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hikepoint',
            name='elevation',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='hikepoint',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
