# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0007_hike_hike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='report_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
