# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0008_tripreport_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreport',
            name='report_image',
        ),
    ]
