# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0010_auto_20161023_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
