# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0011_hike_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='kind',
            field=models.CharField(default='image', max_length=30),
        ),
    ]
