# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0013_auto_20161112_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('movie', 'Movie'), ('other', 'Other')], default='image', max_length=30),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
