# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0014_auto_20161112_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='url',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
