# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0015_auto_20161112_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripdetail',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
