# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0016_auto_20161112_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripdetail',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('movie', 'Movie'), ('other', 'Link'), ('other', 'Other')], default='image', max_length=30),
        ),
    ]
