# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0017_auto_20161112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('movie', 'Movie'), ('link', 'Link'), ('other', 'Other')], default='image', max_length=30),
        ),
    ]
