name: build-deploy-hiking-aws
on:
  push:
    branches:
      - aws

jobs:
  build-deploy-hiking-aws:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_AWS_HOST }}
          username: ${{ secrets.MY_AWS_USER }}
          #password: ${{ secrets.MY_PASSWORD }}
          key: ${{ secrets.MY_AWS_KEY }}
          script: |
             cd ~/my_docker/OwlsNest
             git pull
             docker build -t my_hiking:latest .
             cd ~/shared
             docker-compose -p dockernest up -d
