name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
jobs:
  build-deploy-hiking-nomad:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |

             cd ~/my_docker/OwlsNest
             git pull
             # build for regular rootless deploy 
             docker build -t my_hiking:latest .
            
             # tag for nomad, which uses rootful docker, so needs a pull from a repo
             docker tag my_hiking:latest middle-earth:5000/my_hiking:latest
             docker push middle-earth:5000/my_hiking:latest
            
             # deploy with nomad
             cd $HOME/my_nomad_datacenter/jobs
             nomad stop my_hiking
             nomad run my_hiking.nomad